language: node_js

services:
  - docker

addons:
  ssh_known_hosts: ${MACHINE_URL}

script:
  - echo 'Tests'
  # - docker-compose -f docker-compose.test.yml up --build books users
  - ssh -i ${SSH_KEY} ${MACHINE_URL}
  - ls
