language: node_js
services:
  - docker

env:
  - SERVER_IP_ADDRESS=35.184.79.30

before_install:
  - docker-compose
    -f docker-compose.test.yml up
    --build
    --abort-on-container-exit
    --exit-code-from books books

  - docker-compose
    -f docker-compose.test.yml up
    --build
    --abort-on-container-exit
    --exit-code-from users users

install:
  - openssl aes-256-cbc -K $encrypted_cd2c10753403_key -iv $encrypted_cd2c10753403_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - sudo echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key

script:
  - ssh -i ./deploy_key TravisCIDeployKey@35.184.79.30 < ./deploy.sh
