language: bash
services:
  - docker

addons:
  ssh_known_hosts:
    - 35.184.79.30

before_script:
  - sudo echo -e "Host 35.184.79.30\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

before_install:
  - openssl aes-256-cbc -K $encrypted_cd2c10753403_key -iv $encrypted_cd2c10753403_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
  - cat ~/.ssh/config

script:
  - sudo bash ./deploy.sh
