language: bash
services:
  - docker
addons:
  ssh_known_hosts: 35.184.79.30

before_install:
  - openssl aes-256-cbc -K $encrypted_cd2c10753403_key -iv $encrypted_cd2c10753403_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key

script:
  - './deploy.bash'
