language: node_js

services:
  - docker

addons:
  ssh_known_hosts: 35.184.79.30

script:
  - echo 'Tests'
  # - docker-compose -f docker-compose.test.yml up --build books users
  #   - ${SSH_KEY} >> ./key.pub
  #   - chmod 400 ./key.pub
  - eval `ssh-agent -s`
  - ssh-add - <<< "${SSH_PRIVATE_KEY}"
  - ls ~/.ssh
  - ssh -i ./id_rsa ${MACHINE_URL}
  #   - rm -rf ./key.pub
  - ls
