version: "3.6"

services:
  api-gateway:
    build: ./services/api-gateway
    restart: always
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - books
      - users

  books:
    env_file: .env
    restart: always
    build: ./services/books
    ports:
      - 3031:3031
    depends_on:
      - books-db
    environment:
      WAIT_HOSTS: books-db:27017

  books-db:
    image: mongo:latest
    volumes:
      - ./services/books/data:/data/db
    ports:
      - "27017:27017"

  users:
    env_file: .env
    restart: always
    build: ./services/users
    ports:
      - 3032:3032
    depends_on:
      - users-db
    environment:
      WAIT_HOSTS: users-db:27018

  users-db:
    image: mongo:latest
    command: mongod --port 27018
    volumes:
      - ./services/users/data:/data/db
    ports:
      - "27018:27018"
