version: "3.6"

services:
  api-gateway:
    build: ./services/api-gateway
    restart: always
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - books
      - users

  books:
    env_file: .env
    restart: always
    build: ./services/books
    ports:
      - ${BOOKS_PORT}:${BOOKS_PORT}
    depends_on:
      - books-db
    environment:
      WAIT_HOSTS: books-db:${BOOKS_MONGODB_PORT}

  books-db:
    image: mongo:latest
    volumes:
      - ./services/books/data:/data/db
    ports:
      - "${BOOKS_MONGODB_PORT}:${BOOKS_MONGODB_PORT}"

  users:
    env_file: .env
    restart: always
    build: ./services/users
    ports:
      - ${USERS_PORT}:${USERS_PORT}
    depends_on:
      - users-db
    environment:
      WAIT_HOSTS: users-db:${USERS_MONGODB_PORT}

  users-db:
    image: mongo:latest
    command: mongod --port ${USERS_MONGODB_PORT}
    volumes:
      - ./services/users/data:/data/db
    ports:
      - "${USERS_MONGODB_PORT}:${USERS_MONGODB_PORT}"
