version: "3.6"

services:

  # books:
  #   env_file: .env
  #   build:
  #     context: .
  #     dockerfile: ./services/books/Dockerfile.test

  users:
    env_file: .env
    build:
      context: .
      dockerfile: ./services/users/Dockerfile.test
