version: "3.6"

services:

  books:
    env_file: .env
    build:
      context: ./services/books
      dockerfile: Dockerfile.test

  users:
    env_file: .env
    build:
      context: ./services/users
      dockerfile: Dockerfile.test
